[package]
name = "mlir-sys"
version = "230.0.1"
edition = "2024"
description = "Rust bindings to the MLIR C API."
readme = "README.md"
repository = "https://github.com/mlir-rs/mlir-sys"
license-file = "LICENSE"
keywords = ["llvm", "mlir"]
categories = ["external-ffi-bindings"]
links = "MLIR"

[build-dependencies]
bindgen = "0.73.1"

[features]
no-version-check = []
