name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup
      - run: cargo build
  unit_test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup
      - run: cargo test
  test:
    needs:
      - build
      - unit_test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          for result in ${{ join(needs.*.result, ' ') }}; do
            [ $result = success ]
          done
